### ISSUE TITLE
[OTHER] - Add link to the website in the repository description

### ISSUE THREAD

**Issue by Panquesito7** [BeccaLyria/BeccaLyria.github.io#120]
### What would you like to share?

It'd be great if you could add the link to the website in the repository description

![image](https://user-images.githubusercontent.com/51391473/127724477-4ec0342b-aa3b-4e3c-aeac-6f4c7a55557c.png)

Click on the gear in the repository settings, and add `https://www.beccalyria.com/` in the `Website` field.

### Additional information

Nope.

**Comment by nhcarrigan** [comment]
Resolved 🙂
