### ISSUE TITLE
[BUG] - Becca's avatar image is broken

### ISSUE THREAD

**Issue by TAKANOME-DEV** [BeccaLyria/BeccaLyria.github.io#370]
### What bug did you encounter?

I visited [BeccaLyria.github.io](https://www.beccalyria.com/) and it seems like becca's avatar image is not showing up.

### What did you expect to happen?

I was expecting to see becca's image avatar.

### Screenshots

![becca](https://user-images.githubusercontent.com/79809121/168251883-1c70f4a6-3e76-434a-937d-b7187a976577.png)

**Comment by nhcarrigan** [comment]
Nice catch! The link found here needs to be updated:

https://github.com/BeccaLyria/BeccaLyria.github.io/blob/4edf2b2a0f4a611373e163be03b6b1a77bc39941/src/app/home/home.component.html#L6

The new link should be `https://cdn.nhcarrigan.com/avatars/becca.png`.
