### ISSUE TITLE
Website UI enhancement

### ISSUE THREAD

**Issue by VasuDevrani** [BeccaLyria/BeccaLyria.github.io#461]
### What would you like to share?

Hey!
I would like to make some improvements to the UI of the BeccaLyria website and improve the user experience.
Some of the features and improvements I can produce:

Dark mode
improved responsiveness
UI enhancement
Please assign this task to me. I'd be more than happy to contribute.

Thank you

**Comment by naomi-lgbt** [comment]
Hey there~!

PRs are certainly welcome, though we'd love to see some mocks first!

**Comment by VasuDevrani** [comment]
Thanks for the reply, what kinda mocks? I didn't get.

**Comment by naomi-lgbt** [comment]
Generally, when proposing UI enhancements, it's good to provide example images (usually made with something like Figma) so that the scope of changes is clear.
