### ISSUE TITLE
[CHORE] - Move images to CDN

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/BeccaLyria.github.io#668]
### What work needs to be performed?

We should remove the Becca images from this repository and use the hosted ones from our CDN.

## Art

- Remove the `src/assets/art` folder and all images within
- Update the gallery component in both instances ([1](https://github.com/BeccaLyria/BeccaLyria.github.io/blob/e543e36e04097c5f258edfa386be4c2eb774d19a/src/app/gallery/gallery.component.html#L14) and [2](https://github.com/BeccaLyria/BeccaLyria.github.io/blob/e543e36e04097c5f258edfa386be4c2eb774d19a/src/app/gallery/gallery.component.html#L21)) to point to `https://cdn.naomi.lgbt/becca/art/{{ file }}`, replacing `file` with `selectedArt.fileName` and `art.fileName` respectively.

## Games

- Remove the `src/assets/games` folder and all images within
- Update the games component in both instances ([1](https://github.com/BeccaLyria/BeccaLyria.github.io/blob/e543e36e04097c5f258edfa386be4c2eb774d19a/src/app/games/games.component.html#L5) and [2](https://github.com/BeccaLyria/BeccaLyria.github.io/blob/e543e36e04097c5f258edfa386be4c2eb774d19a/src/app/games/games.component.html#L8)) to point to `https://cdn.naomi.lgbt/becca/games/{{ game.fileName }}`

## Emotes

- Remove the `src/assets/emotes` folder and all images within
- Update the emotes component in both instances ([1](https://github.com/BeccaLyria/BeccaLyria.github.io/blob/e543e36e04097c5f258edfa386be4c2eb774d19a/src/app/emotes/emotes.component.html#L13) and [2](https://github.com/BeccaLyria/BeccaLyria.github.io/blob/e543e36e04097c5f258edfa386be4c2eb774d19a/src/app/emotes/emotes.component.html#L16)) to point to `https://cdn.naomi.lgbt/becca/emotes/{{ emote.fileName }}`

### Additional information

Work may begin on this at any time, however the PR that resolves this issue will not be merged until [the related bot issue](https://github.com/BeccaLyria/discord-bot/issues/1645) is resolved + deployed - to avoid broken images in the bot.

**Comment by Susmita-Dey** [comment]
I wanna work on this issue

**Comment by naomi-lgbt** [comment]
All yours~!
